name: Purser Technology
author: Purser Technology

github: http://www.github.com/roypur
email: post@purser.technology
location: 59°55'44.0400"N 011°04'06.2400"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
